application: adept-storm-600
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /img
  static_dir: templates/img
  
- url: /css
  static_dir: templates/css

- url: /js
  static_dir: templates/js

- url: /.*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
